### PR TITLE
Introduce a Connection Timeout for connecting to Docker

### LINKED ISSUE #45: Timeout and Attach conflict?
At the moment if Docker connection fails then the modem can hang requests. However when using timeout combine with Attach then the two seem to conflict.  Having set my timeout to 1000, it will also still the on-going attach connection even if it has successfully connected. 

The node.js documentation says: "Sets the socket to timeout after timeout milliseconds of inactivity on the socket" where as I want the timeout to be on the initial connection. 

Proposed Solution:
   On Connect / Data / Error we clear the timeout. 

Debug log:
  modem Sending: { path: '/containers/create?Image=',
  method: 'POST',
  port: '2376' } +0ms
  modem Received: {"Id":"a54e6dc2a17dd84493bf1a9335e499bb80a659be990d268cf2e9185cd99db28f","Warnings":null}
 +154ms
  modem Sending: { path: '/containers/a54e6dc2a17dd84493bf1a9335e499bb80a659be990d268cf2e9185cd99db28f/attach?stream=true&stdin=true&stdout=true&stderr=true',
  method: 'POST',
  port: '2376' } +3ms
  modem Sending: { path: '/containers/a54e6dc2a17dd84493bf1a9335e499bb80a659be990d268cf2e9185cd99db28f/start',
  port: '2376' } +29ms
  modem Received:  +199ms
  modem Sending: { path: '/containers/a54e6dc2a17dd84493bf1a9335e499bb80a659be990d268cf2e9185cd99db28f/resize?w=100&h=25',
  method: 'POST',
  port: '2376' } +2ms
  modem Sending: { path: '/containers/a54e6dc2a17dd84493bf1a9335e499bb80a659be990d268cf2e9185cd99db28f/resize?w=118&h=25',
  method: 'POST',
  port: '2376' } +5ms
  modem Received:  +47ms
  modem Received:  +15ms
  modem Timeout of 1000 ms exceeded +971ms

### PR DESCRIPTION
**Pull request by BenHall**
Closes #45

### CODE REVIEW

**Comment by apocas** [comment]
There's already a timeout option adding another will end up being confusing, we should investigate why the existing timeout option isn't firing on your use case.

Did you do any debugging regarding why the 'socket' event was not being triggered here https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L161 ?

**Comment by BenHall** [comment]
Hi, yes, this is the approach I used originally but I found it also timed out the socket when I was using the /attach endpoint which I use to send / receive responses as a tty. 

From the documentation: "Sets the socket to timeout after timeout milliseconds of inactivity on the socket".  Because the /attach stream doesn't have a heartbeat, if you don't send a message for a while then it will timeout which is what I was trying to fix

**Comment by Seikho** [comment]
I was about to about an issue about this as well. The connection timeout would be very useful when working with successfully connected streams that are being incorrectly 'timed out' because of the timeout option.

**Comment by apocas** [comment]
We just have to solve this "connectionTimeout" and/vs "Timeout" options, it will be messy otherwise.

Could we use the same option for both?

**Comment by Seikho** [comment]
I agree that the same option *could* be used for both. However there are probably use cases where it may not work. Such as if you specifically want a request to be terminated because it's taking too long despite it having successfully connected.  
Could the `timeout` for streams behave differently?

**Comment by BenHall** [comment]
Sadly timeout cannot be used due to #45

**Comment by apocas** [comment]
👍

**Pull request merged**
