### PR TITLE
Support agent forwarding over SSH

### PR DESCRIPTION
**Pull request by steverice**
Like #117, add a common SSH option supported by [ssh2](https://github.com/mscdex/ssh2#client-methods).
All we need to do is pass it in the constructor.

### CODE REVIEW

**Comment by bwateratmsft** [comment]
Should we consider just passing _everything_ in `options`, just overriding `agent` with `authAgent`?

**Comment by steverice** [comment]
@apocas what do you think?

**Comment by apocas** [comment]
I totally agree, we need to do something about these options.

Instead of passing everything that comes inside the options object, because it could potentially lead to problems inside ssh2.
We could just use something like "options.sshOptions", then everything that comes inside sshOptions is automatically sent to ssh in https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L210.
(everything inside sshOptions would be merged in {host': self.host, 'port': self.port, 'username': self.username, 'password': self.password})

This way we avoid sending a lot of stuff to ssh2 lib and there's an object exactly for that.

**Comment by steverice** [comment]
@bwateratmsft @apocas thoughts on #119?

**Comment by apocas** [comment]
Published in v2.1.3

**Pull request merged**
