### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by oliversalzburg**
Update all dependencies to the latest version. Tests still pass fine.

### CODE REVIEW

**Comment by apocas** [comment]
jsonstream had issues https://github.com/apocas/dockerode/issues/142#issuecomment-109048277

If dockerode's tests are passing, everything should be OK. Nevertheless needs to be double checked.

**Comment by oliversalzburg** [comment]
I was mostly caring about `debug`, because the output did not match that of other parts of our application. So I thought, why not see if all can be upgraded :)

**Comment by TooTallNate** [comment]
👍

**Comment by apocas** [comment]
Debug bumped.

**Pull request closed without merging**
