### PR TITLE
rely on core querystring package

### PR DESCRIPTION
**Pull request by briceburg**
@apocas 

this is related to https://github.com/apocas/dockerode/issues/196

it's a tiny change and perhaps _not ready to merge yet_. what do you think about replacing this package with [qs](https://www.npmjs.com/package/qs) which supports nested objects, and should allow:

```js
docker.listContainers({
  "filters": {
    "label": ["staging","env=green"]
  }
});
```

otherwise we can keep things as-is, and I can update the listContainers example showing how to pass filters as a string (which is a bit foreign to work with): e.g. 

```js
docker.listContainers({
  "filters": '{"label": ["staging","env=green"]}'
});
```

please let me know how you'd like to proceed. if you want to use qs, I can test thoroughly and amend this PR.

Thanks!

### CODE REVIEW

**Comment by apocas** [comment]
Would love to see `dockerode`'s test suite with `qs` and see what happens.

We need to take in account that there may be people already doing this in their implementation.
Being this said, if `qs` does not do weird things if the data is already escaped (ex: double escaping), great.
Otherwise we need some validation code in order to avoid this being a breaking change and consequently be delayed to the next major release :)

**Comment by briceburg** [comment]
OK great. I've setup a repository to perform the dockerode test suite against a patched to use `qs` docker-modem. I had to relax the timeout for listing images [I really should clean up dangling images!], but the good news is all tests passed. Repository is: https://github.com/briceburg/dockerode/tree/briceburg/filter-tests

```
...
62 passing (35s)
```

Excellent foresight re: verifying `qs` will not double-escape. 

When I next visit this I'll incorporate mocha tests covering qs, double escaping, and the ability to send filters as intended.

**Comment by briceburg** [comment]
Unfortunately the `qs` library does not serialize structured data to something the docker api expects. It turns objects into associative arrays -- and I tried about 300 mutations of arrays,strings, and maps with different combinations of options passed to qs.stringify. 

I'll continue to investigate a friendly alternative -- and think we may need to introduce a utility/helper method that uses JSON.stringify and transforms our labels object to an array of key=value pairs. 

For instance, this code works

```js
it("should appear in listings filtering a array of labels", function(done){
      docker.listContainers({
        "limit": 3,
        "filters": JSON.stringify({"label": ["dockerode-test", "dockerode-test-value=works"]})
      }, function(err, data){
        expect(data.length).to.equal(1);
        done();
      });
    });
```

while this does not

```
  var labels = {
      "dockerode-test": "",
      "dockerode-test-value": "works"
    };


it("should appear in listings filtering a array of labels", function(done){
      docker.listContainers({
        "limit": 3,
        "filters": JSON.stringify({"label": labels})
      }, function(err, data){
        expect(data.length).to.equal(1);
        done();
      });
    });
```

do you think this is worth pursuing? one idea is the following:

```js

  var labels = {
      "dockerode-test": "",
      "dockerode-test-value": "works"
    };

var filterHelper = function(key, objOrArray){
// ...
}


  it("should appear in listings filtering a array of labels", function(done){
      docker.listContainers({
        "limit": 3,
        "filters": filterHelper("label", labels)
      }, function(err, data){
        expect(data.length).to.equal(1);
        done();
      });
    });

```

thanks!

**Comment by briceburg** [comment]
I am closing this PR in favor of PR #58 and PR #59

**Pull request closed without merging**
